interface Theme {
    dir?: string; // 'ltr' or 'rtl'
    green?: boolean;
    blue?: boolean;
    dark?: boolean;
    minisidebar?: boolean;
    boxed?: boolean;
    danger?: boolean;
    showHide?: boolean;
    defaultColor?: boolean;
}
export interface User {
  name: string;
  role: string;
  mail?: string;
  id: string;
  community?: string;
  supervisor?: string;
  mobilePhoneNumber?: string;
  idNumber?: string;
}
export const users: User[] = [
  {
    name: 'admin',
    role: 'admin',
    mail: 'mail@test.com',
    mobilePhoneNumber: '18792778933',
    id: '000'
  }, {
    name: '小花',
    role: 'patient',
    supervisor: 'doctor1',
    mail: 'mail@test.com',
    mobilePhoneNumber: '18792778933',
    id: '001',
    community: '长安',
    idNumber: '000000000000000001'
  }, {
    name: '小黄',
    role: 'patient',
    supervisor: 'doctor1',
    mail: 'mail@test.com',
    mobilePhoneNumber: '18792778933',
    id: '002',
    community: '长安',
    idNumber: '000000000000000002'
  }, {
    name: '小绿',
    role: 'patient',
    supervisor: 'doctor2',
    mail: 'mail@test.com',
    mobilePhoneNumber: '18792778933',
    id: '003',
    community: '长安',
    idNumber: '000000000000000003'
  }, {
    name: '小红',
    role: 'patient',
    supervisor: 'doctor2',
    mail: 'mail@test.com',
    mobilePhoneNumber: '18792778933',
    id: '004',
    community: '碑林',
    idNumber: '000000000000000004'
  }, {
    name: 'doctor1',
    role: 'doctor',
    supervisor: 'community1',
    mail: 'mail@test.com',
    mobilePhoneNumber: '18792778933',
    id: '005',
    community: '长安'
  }, {
    name: 'doctor2',
    role: 'doctor',
    supervisor: 'community1',
    mail: 'mail@test.com',
    mobilePhoneNumber: '18792778933',
    id: '006',
    community: '长安'
  }, {
    name: 'doctor3',
    role: 'doctor',
    supervisor: 'community2',
    mail: 'mail@test.com',
    mobilePhoneNumber: '18792778933',
    id: '007',
    community: '碑林'
  }, {
    name: 'community1',
    role: 'community',
    community: '长安',
    supervisor: 'admin',
    mail: 'mail@test.com',
    mobilePhoneNumber: '18792778933',
    id: '008'
  }, {
    name: 'community2',
    role: 'community',
    community: '碑林',
    supervisor: 'admin',
    mail: 'mail@test.com',
    mobilePhoneNumber: '18792778933',
    id: '009'
  }
];
