export const treedata = {
 '住院病案首页提取信息': {
      '住院号': 'number',
      '病案号': 'number',
        '名字': 'string' ,
        '出生年月': 'date',
        '年龄': 'number' ,
        '体重': 'number' ,
        '身高': 'number' ,
        '性别': 'string' ,
        '居住地': 'string' ,
        '出生地': 'string' ,
        '职业': 'string' ,
        '民族': 'string' ,
        '联系电话': 'number' ,
        '联系人姓名': 'string' ,
        '联系人电话': 'number' ,
        '入院时间': 'date' ,
        '入院诊断': 'string' ,
        '出院时间': 'date' ,
        '出院诊断': 'string' ,
        '实际住院天数': 'number',
        '病理号': 'number',
        '病理诊断': 'string',
        '手术名称': 'string',
        '麻醉方式': 'string',
    },
    '入院病历': {
        '主诉': 'string' ,
        '现病史': 'string' ,
        '治疗时间': 'string' ,
        '治疗次数': 'number' ,
        '治疗方式': 'string' ,
        '靶向治疗': 'string' ,
        '靶向治疗剂量': 'string' ,
        '化疗方案': 'string' ,
        '化疗剂量': 'string' ,
        '血压': 'number' ,
        '体重': 'number' ,
        '身高': 'number' ,
        '手术史': 'string' ,
        '绝经日期': 'date' ,
        '月经': 'string' ,
        '伴随疾病': 'string' ,
        '家族史': 'string' ,
        '专科体检': 'string' ,
      },
    '一般检查项目': {
       '血常规': 'number' ,
        '尿常规': 'number' ,
        '粪常规': 'number' ,
        '生化': 'number' ,
        '肝肾功': 'number' ,
        '风湿免疫抗体': 'number' ,
        '女性性激素': 'number' ,
        '凝血系列': 'number' ,
        '女性肿瘤标志物': 'number' ,
        '甲功八项': 'number' ,
        '胸片': '' ,
        '心电图': '' ,
        '子宫B超': '' ,
        '胸部CT': '' ,
        '脑部CT': '',
        '腹部CT': '' ,
        '心脏彩超': '' ,
    },
   '特殊检查项目': {
        '肿瘤位置': 'string' ,
        '肿瘤大小': 'number' ,
        '肿瘤大小（T）': 'string' ,
        '淋巴结转移个数': 'number' ,
        '淋巴结（N）': '' ,
        '病理分期（pN）': '' ,
        '远处转移（M）': 'string' ,
        'tnm分期': '' ,
        '临床分期': 'number' ,
        '组织学分级': 'string' ,
        '免疫组化': 'string' ,
        '补充检查': 'string' ,
        '乳腺B超': '' ,
        '乳腺磁共振': '' ,
        '乳腺钼靶': '' ,
        '乳管镜': '' ,
   },
  '治疗方式': {
        '化疗方案': 'string' ,
        '化疗剂量': '' ,
        '化疗次数': 'number' ,
   },
  '出院记录': {
        '主诉' : 'string',
   },
  '随访一般项目': {
        '随访时间': 'string' ,
        '生存状态': 'string' ,
        '近期治疗方式': 'string' ,
        '近期治疗时间': 'date' ,
        '新发疾病': 'string' ,
        '病情转归': 'string' ,
        '疾病进展': 'string' ,
        '死亡原因': 'string',
  }
}
;
export const gettreedata = () => {
    return treedata;
};


