export class FollowHypertensionList {
  items = [
    {
      step_description: '常规检查',
      items: [
        {
          type: 'table',
          title: '常规检查（必填项）',
          required: true,
          cols: 5,
          layout: [
            { type: 'text', cols: 2, rows: 1, text: '血压：' },
            { type: 'input_double_with_text', cols: 3, rows: 1, left_text: '收缩压', center_text: 'mmHg，舒张压', right_text: 'mmHg', key_value: [{ _key: '血压_收缩压', _value: ''}, { _key: '血压_舒张压', _value: ''}] , disabled: false },
            { type: 'text', cols: 2, rows: 1, text: '体重：' },
            { type: 'input_with_text', cols: 3, rows: 1, right_text: 'kg', key_value: { _key: '体重', _value: ''}, disabled: false },
            { type: 'text', cols: 2, rows: 1, text: '腰围：' },
            { type: 'input_with_text', cols: 3, rows: 1, right_text: 'cm', key_value: { _key: '腰围', _value: ''}, disabled: false },
            { type: 'text', cols: 2, rows: 1, text: '心率：' },
            { type: 'input_with_text', cols: 3, rows: 1, right_text: '次/分', key_value: { _key: '心率', _value: ''}, disabled: false }
          ]
        }
      ]
    },
    {
      step_description: '症状',
      items: [
        {
          type: 'table',
          title: '症状',
          required: true,
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '高血压：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无高血压', _value: '' }},
            { type: 'radio', cols: 2, rows: 1, options: ['既往已知高血压', '初次发现高血压'], key_value: { _key: '高血压既往', _value: '' }, disabled: true, disabled_ref_c: { id: 1, condition: ['有'] }},
            { type: 'text', cols: 1, rows: 1, text: '发现高血压几年：' },
            { type: 'input', cols: 1, rows: 1, right_text: '年', key_value: { _key: '发现高血压几年', _value: ''}, disabled: true, disabled_ref_c: { id: 2, condition: ['既往已知高血压'] }},
            { type: 'text', cols: 1, rows: 1, text: '发现方式：' },
            { type: 'radio', cols: 5, rows: 1, options: ['体检获取', '无意中获得', '因症状就诊发现'], key_value: { _key: '高血压发现方式', _value: '' }, disabled: true, disabled_ref_c: { id: 1, condition: ['有'] }},
            { type: 'text', cols: 1, rows: 1, text: '头晕：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无头晕', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '心悸：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无心悸', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '气短：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无气短', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '胸痛：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无胸痛', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '疲劳：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无疲劳', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '颈椎板紧：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无颈椎板紧', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '鼻出血：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无鼻出血', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '视物模糊：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无视物模糊', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '恶心：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无恶心', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '呕吐：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无呕吐', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '有无呕吐物：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无呕吐物', _value: '' }, disabled: true, disabled_ref_c: { id: 26, condition: ['有'] }},
            { type: 'radio', cols: 2, rows: 1, options: ['胃内溶物', '其他'], key_value: { _key: '呕吐物', _value: '' }, disabled: true, disabled_ref_c: { id: 28, condition: ['有'] }},
            { type: 'text', cols: 1, rows: 1, text: '间歇性跛行：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无间歇性跛行', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '有无下肢疼：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无下肢疼', _value: '' }, disabled: true, disabled_ref_c: { id: 31, condition: ['有'] }},
            { type: 'text', cols: 1, rows: 1, text: '意识模糊：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无意识模糊', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '昏迷：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无昏迷', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '抽搐：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无'], key_value: { _key: '有无抽搐', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '偏瘫：' },
            { type: 'radio', cols: 1, rows: 1, options: ['左', '右'], key_value: { _key: '有无偏瘫', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '其它：' },
            { type: 'input', cols: 5, rows: 1,  key_value: { _key: '其它', _value: '' }}
            // { type: 'text', cols: 1, rows: 1, text: '头晕：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否头晕', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '头痛：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否头痛', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '呕吐：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否呕吐', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '颈椎板紧：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否颈椎板紧', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '疲劳：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否疲劳', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '心悸：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否心悸', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '视力模糊：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否视力模糊', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '鼻出血：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否鼻出血', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '眩晕：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否眩晕', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '意识模糊：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否意识模糊', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '昏迷：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否昏迷', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '局灶性或全身抽搐：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否局灶性或全身抽搐', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '偏瘫：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否偏瘫', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '失语：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否失语', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '胸痛：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否胸痛', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '气短：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '是否气短', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '其它：' },
            // { type: 'input', cols: 7, rows: 1,  key_value: { _key: '其它', _value: '' }},
          ]
        }
      ]
    },
    {
      step_description: '新发事件',
      items: [
        {
          type: 'table',
          title: '新发心脑血管事件',
          required: false,
          cols: 12,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '心绞痛：' },
            { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '新发心绞痛', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '发生时间：' },
            { type: 'date', cols: 2, rows: 1, key_value: { _key: '新发心绞痛发生时间', _value: '' } , disabled: true, disabled_ref_c: { id: 1, condition: ['是'] }},
            { type: 'text', cols: 2, rows: 1, text: '主诉、诊断依据、治疗措施、转归：' },
            { type: 'input', cols: 5, rows: 1,  key_value: { _key: '新发心绞痛主诉', _value: '' }, disabled: true, disabled_ref_c: { id: 1, condition: ['是'] }},
            { type: 'text', cols: 1, rows: 1, text: '急性心肌梗死：' },
            { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '新发急性心肌梗死', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '发生时间：' },
            { type: 'date', cols: 2, rows: 1, key_value: { _key: '新发急性心肌梗死发生时间', _value: '' } , disabled: true, disabled_ref_c: { id: 7, condition: ['是'] }},
            { type: 'text', cols: 2, rows: 1, text: '主诉、诊断依据、治疗措施、转归：' },
            { type: 'input', cols: 5, rows: 1,  key_value: { _key: '新发急性心肌梗死主诉', _value: '' }, disabled: true, disabled_ref_c: { id: 7, condition: ['是'] }},
            { type: 'text', cols: 1, rows: 1, text: 'PCI：' },
            { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '新发PCI', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '发生时间：' },
            { type: 'date', cols: 2, rows: 1, key_value: { _key: '新发PCI发生时间', _value: '' }, disabled: true, disabled_ref_c: { id: 13, condition: ['是'] }},
            { type: 'text', cols: 2, rows: 1, text: '主诉、诊断依据、治疗措施、转归：' },
            { type: 'input', cols: 5, rows: 1,  key_value: { _key: '新发PCI主诉', _value: '' }, disabled: true, disabled_ref_c: { id: 13, condition: ['是'] }},
            { type: 'text', cols: 1, rows: 1, text: '冠脉搭桥：' },
            { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '新发心绞痛', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '发生时间：' },
            { type: 'date', cols: 2, rows: 1, key_value: { _key: '新发冠脉搭桥发生时间', _value: '' }, disabled: true, disabled_ref_c: { id: 19, condition: ['是'] }},
            { type: 'text', cols: 2, rows: 1, text: '主诉、诊断依据、治疗措施、转归：' },
            { type: 'input', cols: 5, rows: 1,  key_value: { _key: '新发冠脉搭桥主诉', _value: '' }, disabled: true, disabled_ref_c: { id: 19, condition: ['是'] }},
            { type: 'text', cols: 1, rows: 1, text: '心力衰竭：' },
            { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '新发心力衰竭', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '发生时间：' },
            { type: 'date', cols: 2, rows: 1, key_value: { _key: '新发心力衰竭发生时间', _value: '' }, disabled: true, disabled_ref_c: { id: 25, condition: ['是'] }},
            { type: 'text', cols: 2, rows: 1, text: '主诉、诊断依据、治疗措施、转归：' },
            { type: 'input', cols: 5, rows: 1,  key_value: { _key: '新发心力衰竭主诉', _value: '' }, disabled: true, disabled_ref_c: { id: 25, condition: ['是'] }},
            { type: 'text', cols: 1, rows: 1, text: '一过性脑缺血发作：' },
            { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '新发一过性脑缺血发作', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '发生时间：' },
            { type: 'date', cols: 2, rows: 1, key_value: { _key: '新发一过性脑缺血发作发生时间', _value: '' }, disabled: true, disabled_ref_c: { id: 31, condition: ['是'] }},
            { type: 'text', cols: 2, rows: 1, text: '主诉、诊断依据、治疗措施、转归：' },
            { type: 'input', cols: 5, rows: 1,  key_value: { _key: '新发一过性脑缺血发作主诉', _value: '' }, disabled: true, disabled_ref_c: { id: 31, condition: ['是'] }},
            { type: 'text', cols: 1, rows: 1, text: '脑卒中：' },
            { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '新发脑卒中', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '发生时间：' },
            { type: 'date', cols: 2, rows: 1, key_value: { _key: '新发脑卒中发生时间', _value: '' }, disabled: true, disabled_ref_c: { id: 37, condition: ['是'] }},
            { type: 'text', cols: 2, rows: 1, text: '主诉、诊断依据、治疗措施、转归：' },
            { type: 'input', cols: 5, rows: 1,  key_value: { _key: '新发脑卒中主诉', _value: '' }, disabled: true, disabled_ref_c: { id: 37, condition: ['是'] }},
            { type: 'text', cols: 1, rows: 1, text: '住院：' },
            { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '新发住院', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '发生时间：' },
            { type: 'date', cols: 2, rows: 1, key_value: { _key: '新发住院发生时间', _value: '' }, disabled: true, disabled_ref_c: { id: 43, condition: ['是'] }},
            { type: 'text', cols: 2, rows: 1, text: '主诉、诊断依据、治疗措施、转归：' },
            { type: 'input', cols: 5, rows: 1,  key_value: { _key: '新发住院主诉', _value: '' }, disabled: true, disabled_ref_c: { id: 43, condition: ['是'] }},
            { type: 'text', cols: 1, rows: 1, text: '死亡：' },
            { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '新发死亡', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '发生时间：' },
            { type: 'date', cols: 2, rows: 1, key_value: { _key: '新发死亡发生时间', _value: '' }, disabled: true, disabled_ref_c: { id: 49, condition: ['是'] }},
            { type: 'text', cols: 2, rows: 1, text: '主诉、诊断依据、治疗措施、转归：' },
            { type: 'input', cols: 5, rows: 1,  key_value: { _key: '新发死亡主诉', _value: '' }, disabled: true, disabled_ref_c: { id: 49, condition: ['是'] }},
          ]
        },
        {
          type: 'table',
          title: '其它新发事件',
          required: false,
          cols: 12,
          layout: [
            { type: 'text', cols: 2, rows: 2, text: '有无其它新发事件：' },
            { type: 'radio', cols: 1, rows: 2, options: ['有', '无'], key_value: { _key: '新发死亡', _value: '' }},
            { type: 'text', cols: 2, rows: 2, text: '如果有，那么有：' },
            {
              type: 'checkbox',
              cols: 7,
              rows: 2,
              options: [
                '空腹血糖受损', '糖耐量受损', '糖尿病', '血脂异常', '血同型半胱氨酸升高', '左心室肥厚', '颈动脉超声IMT≥0.9mm或动脉粥样斑块',
                '糖尿病肾病', '肾功能受损轻', '肾功能受损重', '闭塞性周围动脉粥样硬化', '视网膜病变Ⅰ、Ⅱ级', '视网膜病变Ⅲ、Ⅳ级'
              ],
              key_value: [
                { _key: '空腹血糖受损', _value: '' },
                { _key: '糖耐量受损', _value: '' },
                { _key: '糖尿病', _value: '' },
                { _key: '血脂异常', _value: '' },
                { _key: '血同型半胱氨酸升高', _value: '' },
                { _key: '左心室肥厚', _value: '' },
                { _key: '颈动脉超声IMT≥0.9mm或动脉粥样斑块', _value: '' },
                { _key: '糖尿病肾病', _value: '' },
                { _key: '肾功能受损轻', _value: '' },
                { _key: '肾功能受损重', _value: '' },
                { _key: '闭塞性周围动脉粥样硬化', _value: '' },
                { _key: '视网膜病变Ⅰ、Ⅱ级', _value: '' },
                { _key: '视网膜病变Ⅲ、Ⅳ级', _value: '' },
              ],
              disabled: true,
              disabled_ref_c: { id: 1, condition: ['有'] }}
          ]
        }
      ]
    },
    {
      step_description: '饮食生活习惯',
      items: [
        {
          type: 'table',
          title: '饮食生活习惯有无改变',
          displayControl: { check: true },
          required: true,
          cols: 2,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '摄盐量 <6克/日：' },
            { type: 'radio', cols: 1, rows: 1, options: ['达标', '不达标'], key_value: { _key: '摄盐量', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '碳酸类：' },
            { type: 'radio', cols: 1, rows: 1, options: ['达标', '不达标'], key_value: { _key: '碳酸类', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '油脂 食油20~25克/日，且总脂肪<30%总热量，且饱和脂肪<10%总热量：' },
            { type: 'radio', cols: 1, rows: 1, options: ['达标', '不达标'], key_value: { _key: '油脂', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '蔬菜 400~500克/日：' },
            { type: 'radio', cols: 1, rows: 1, options: ['达标', '不达标'], key_value: { _key: '蔬菜', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '水果 100克/日：' },
            { type: 'radio', cols: 1, rows: 1, options: ['达标', '不达标'], key_value: { _key: '水果', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '戒烟：' },
            { type: 'radio', cols: 1, rows: 1, options: ['达标', '不达标'], key_value: { _key: '戒烟', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '饮酒 男<30克/日,女<20克/日，孕妇不饮酒：' },
            { type: 'radio', cols: 1, rows: 1, options: ['达标', '不达标'], key_value: { _key: '饮酒', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '运动量 30分钟运动/次，每周3~5次：' },
            { type: 'radio', cols: 1, rows: 1, options: ['达标', '不达标'], key_value: { _key: '运动量', _value: '' }},
          ]
        }
      ]
    },
    {
      step_description: '体征',
      items: [
        {
          type: 'table',
          title: '体征有无改变',
          displayControl: { check: true },
          required: true,
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '血压：' },
            { type: 'input_double_with_text', cols: 2, rows: 1, left_text: '收缩压', center_text: 'mmHg，舒张压', right_text: 'mmHg', key_value: [{ _key: '血压_收缩压', _value: ''}, { _key: '血压_舒张压', _value: ''}] , disabled: false },
            { type: 'text', cols: 1, rows: 1, text: '既往最高血压：' },
            { type: 'input_double_with_text', cols: 2, rows: 1, left_text: '收缩压', center_text: 'mmHg，舒张压', right_text: 'mmHg', key_value: [{ _key: '既往最高血压_收缩压', _value: ''}, { _key: '既往最高血压_舒张压', _value: ''}] , disabled: false },
            { type: 'text', cols: 1, rows: 1, text: '踝臂血压：' },
            { type: 'input_double_with_text', cols: 2, rows: 1, left_text: '收缩压', center_text: 'mmHg，舒张压', right_text: 'mmHg', key_value: [{ _key: '踝臂血压_收缩压', _value: ''}, { _key: '踝臂血压_舒张压', _value: ''}] , disabled: false },
            { type: 'text', cols: 1, rows: 1, text: '双下肢血压：' },
            { type: 'input_double_with_text', cols: 2, rows: 1, left_text: '收缩压', center_text: 'mmHg，舒张压', right_text: 'mmHg', key_value: [{ _key: '双下肢血压_收缩压', _value: ''}, { _key: '双下肢血压_舒张压', _value: ''}] , disabled: false },
            { type: 'text', cols: 1, rows: 1, text: '脉搏：' },
            { type: 'input_with_text', cols: 5, rows: 1, right_text: '次/分', key_value: { _key: '脉搏', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '身高/体重：' },
            { type: 'input_double_with_text', cols: 2, rows: 1, left_text: '身高', center_text: 'cm，体重', right_text: 'kg', key_value: [{ _key: '身高', _value: ''}, { _key: '体重', _value: ''}] , disabled: false, calculate: { calculate_type: 'BMI', calculate_ref: 7, key_ref: ['身高', '体重'] } },
            { type: 'text', cols: 1, rows: 1, text: '体重指数(BMI)：' },
            { type: 'input_with_text', cols: 2, rows: 1, right_text: 'kg/m^2', key_value: { _key: '体重指数', _value: ''}, disabled: true},
            { type: 'text', cols: 1, rows: 1, text: '腰围：' },
            { type: 'input_with_text', cols: 2, rows: 1, right_text: 'cm', key_value: { _key: '腰围', _value: ''}},
            { type: 'text', cols: 1, rows: 1, text: '臀围：' },
            { type: 'input_with_text', cols: 2, rows: 1, right_text: 'cm', key_value: { _key: '臀围', _value: ''}},

            { type: 'text', cols: 1, rows: 2, text: '肺部：' },
            { type: 'text', cols: 1, rows: 1, text: '轮廓：' },
            { type: 'radio', cols: 1, rows: 1, options: ['正常', '异常', '未测'], key_value: { _key: '轮廓', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '异常描述：' },
            { type: 'input', cols: 2, rows: 1, key_value: { _key: '肺部轮廓异常描述', _value: ''}, disabled: true, disabled_ref_c: { id: 20, condition: ['异常'] }},
            { type: 'text', cols: 1, rows: 1, text: '啰音：' },
            { type: 'radio', cols: 2, rows: 1, options: ['未闻及', '干啰音', '湿啰音', '其它', '未测'], key_value: { _key: '啰音', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '呼吸音：' },
            { type: 'radio', cols: 1, rows: 1, options: ['正常', '异常', '未测'], key_value: { _key: '呼吸音', _value: '' }},
            { type: 'text', cols: 1, rows: 4, text: '心脏：' },
            { type: 'text', cols: 1, rows: 1, text: '心率：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '次/分', key_value: { _key: '心率', _value: ''}},
            // { type: 'text', cols: 1, rows: 1, text: '心率：' },
            { type: 'radio', cols: 3, rows: 1, options: ['齐', '不齐', '未测'], key_value: { _key: '心率', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '心界：' },
            { type: 'radio', cols: 2, rows: 1, options: ['正常', '增大', '未查'], key_value: { _key: '心界', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '心音亢进：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无', '未查'], key_value: { _key: '心音亢进', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '杂音：' },
            { type: 'radio', cols: 1, rows: 1, options: ['有', '无', '未查'], key_value: { _key: '杂音', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '听诊：' },
            { type: 'input', cols: 2, rows: 1, key_value: { _key: '听诊', _value: ''}, disabled: true, disabled_ref_c: { id: 36, condition: ['有'] }},
            { type: 'text', cols: 1, rows: 1, text: '动脉杂音：' },
            { type: 'radio', cols: 4, rows: 1, options: ['有', '无', '未查'], key_value: { _key: '动脉杂音', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '心界增大：' },
            // { type: 'radio', cols: 2, rows: 1, options: ['否', '是', '未测'], key_value: { _key: '心界增大', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '主动脉瓣区第2心音亢进：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['否', '是', '未测'], key_value: { _key: '主动脉瓣区第2心音亢进', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '杂音：' },
            // { type: 'radio', cols: 2, rows: 1, options: ['无', '有', '未测'], key_value: { _key: '杂音', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '腹部肿块：' },
            { type: 'radio', cols: 5, rows: 1, options: ['有', '无', '未测'], key_value: { _key: '腹部肿块', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '下肢水肿：' },
            // { type: 'radio', cols: 5, rows: 1, options: ['无', '单侧', '双侧不对称', '双侧对称', '未测'], key_value: { _key: '下肢水肿', _value: '' }},
            { type: 'text', cols: 1, rows: 2, text: '下肢：' },
            { type: 'text', cols: 1, rows: 1, text: '颜色（描述）：' },
            { type: 'input', cols: 1, rows: 1, key_value: { _key: '下肢颜色描述', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '皮温：' },
            { type: 'radio', cols: 2, rows: 1, options: ['正常', '异常', '未测'], key_value: { _key: '下肢水肿', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '水肿：' },
            { type: 'radio', cols: 4, rows: 1, options: ['无', '单侧', '双侧不对称', '双侧对称', '未测'], key_value: { _key: '下肢水肿', _value: '' }},
            { type: 'text', cols: 1, rows: 1, text: '周围血管征：' },
            { type: 'radio', cols: 5, rows: 1, options: ['有', '无', '未查'], key_value: { _key: '周围血管征', _value: '' }}
            // { type: 'input_double_with_text', cols: 2, rows: 1, left_text: '收缩压', center_text: 'mmHg，舒张压', right_text: 'mmHg', key_value: [{ _key: '血压_收缩压', _value: ''}, { _key: '血压_舒张压', _value: ''}] , disabled: false },
            // { type: 'text', cols: 1, rows: 1, text: '既往最高血压：' },
            // { type: 'input_double_with_text', cols: 2, rows: 1, left_text: '既往最高收缩压', center_text: 'mmHg，既往最高舒张压', right_text: 'mmHg', key_value: [{ _key: '既往最高血压_收缩压', _value: ''}, { _key: '既往最高血压_舒张压', _value: ''}] , disabled: false },
            // { type: 'text', cols: 1, rows: 1, text: '身高/体重：' },
            // { type: 'input_double_with_text', cols: 2, rows: 1, left_text: '身高', center_text: 'cm，体重', right_text: 'kg', key_value: [{ _key: '身高', _value: ''}, { _key: '体重', _value: ''}] , disabled: false, calculate: { calculate_type: 'BMI', calculate_ref: 7, key_ref: ['身高', '体重'] } },
            // { type: 'text', cols: 1, rows: 1, text: '体重指数：' },
            // { type: 'input_with_text', cols: 2, rows: 1, right_text: 'kg/m^2', key_value: { _key: '体重指数', _value: ''}, disabled: true},
            // { type: 'text', cols: 1, rows: 1, text: '腰围：' },
            // { type: 'input_with_text', cols: 2, rows: 1, right_text: 'cm', key_value: { _key: '腰围', _value: ''}},
            // { type: 'text', cols: 1, rows: 1, text: '臀围：' },
            // { type: 'input_with_text', cols: 2, rows: 1, right_text: 'cm', key_value: { _key: '臀围', _value: ''}},
            // { type: 'text', cols: 1, rows: 1, text: '心率：' },
            // { type: 'input_with_text', cols: 5, rows: 1, right_text: '次/分', key_value: { _key: '心率', _value: ''}},
            // { type: 'text', cols: 1, rows: 1, text: '肺部：' },
            // { type: 'text', cols: 1, rows: 1, text: '呼吸音：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['正常', '异常', '未测'], key_value: { _key: '呼吸音', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '啰音：' },
            // { type: 'radio', cols: 2, rows: 1, options: ['未闻及', '干啰音', '湿啰音', '其它', '未测'], key_value: { _key: '啰音', _value: '' }},
            // { type: 'text', cols: 1, rows: 2, text: '心脏：' },
            // { type: 'text', cols: 1, rows: 1, text: '心率：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['齐', '不齐', '未测'], key_value: { _key: '心率', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '心界增大：' },
            // { type: 'radio', cols: 2, rows: 1, options: ['否', '是', '未测'], key_value: { _key: '心界增大', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '主动脉瓣区第2心音亢进：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['否', '是', '未测'], key_value: { _key: '主动脉瓣区第2心音亢进', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '杂音：' },
            // { type: 'radio', cols: 2, rows: 1, options: ['无', '有', '未测'], key_value: { _key: '杂音', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '下肢水肿：' },
            // { type: 'radio', cols: 5, rows: 1, options: ['无', '单侧', '双侧不对称', '双侧对称', '未测'], key_value: { _key: '下肢水肿', _value: '' }},
            // { type: 'text', cols: 1, rows: 2, text: '动脉杂音：' },
            // { type: 'text', cols: 1, rows: 1, text: '颈动脉：' },
            // { type: 'radio', cols: 1, rows: 1, options: ['无', '有', '未测'], key_value: { _key: '动脉杂音_颈动脉', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '腹部动脉：' },
            // { type: 'radio', cols: 2, rows: 1, options: ['无', '有', '未测'], key_value: { _key: '动脉杂音_腹部动脉', _value: '' }},
            // { type: 'text', cols: 1, rows: 1, text: '股动脉：' },
            // { type: 'radio', cols: 4, rows: 1, options: ['无', '有', '未测'], key_value: { _key: '动脉杂音_股动脉', _value: '' }}
          ]
        }
      ]
    },
    {
      step_description: '实验室检查',
      items: [
        {
          type: 'table',
          title: '血常规：',
          required: false,
          displayControl: { check: false },
          cols: 4,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 3, rows: 1, key_value: { _key: '血常规检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '红细胞计数(RBC)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '×10^12/L', key_value: { _key: '红细胞计数', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '血红蛋白(Hb)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'g/L', key_value: { _key: '血红蛋白', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '白细胞计数(WBC)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '×10^9/L', key_value: { _key: '白细胞计数', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '血小板计数(PLT)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '×10^9/L', key_value: { _key: '血小板计数', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '尿常规：',
          required: false,
          displayControl: { check: false },
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 5, rows: 1, key_value: { _key: '尿常规检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '外观：' },
            { type: 'input', cols: 1, rows: 1, key_value: { _key: '尿常规外观', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: 'PH：' },
            { type: 'input', cols: 1, rows: 1, key_value: { _key: 'PH', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '比重：' },
            { type: 'input', cols: 1, rows: 1, key_value: { _key: '比重', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '尿蛋白(PRO)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'g/L', key_value: { _key: '尿蛋白(PRO)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '或者 + - 描述符：' },
            { type: 'radio', cols: 3, rows: 1, options: [ '-', '+-', '++', '+++', '++++'], key_value: { _key: '尿蛋白(PRO)+-描述符', _value: ''} },
            { type: 'text', cols: 1, rows: 1, text: '尿糖(GLU)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L', key_value: { _key: '尿糖(GLU)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '或者 + - 描述符：' },
            { type: 'radio', cols: 3, rows: 1, options: [ '-', '+-', '++', '+++', '++++'], key_value: { _key: '尿糖(GLU)+-描述符', _value: ''} },
            { type: 'text', cols: 1, rows: 1, text: '酮体(KET)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L', key_value: { _key: '酮体(KET)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '或者 + - 描述符：' },
            { type: 'radio', cols: 3, rows: 1, options: [ '-', '+-', '++', '+++', '++++'], key_value: { _key: '酮体(KET)+-描述符', _value: ''} },
            { type: 'text', cols: 1, rows: 1, text: '尿胆红素(BIL)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'umol/L', key_value: { _key: '尿胆红素(BIL)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: 'RBC：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '/ul', key_value: { _key: 'RBC', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: 'WBC：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '/ul', key_value: { _key: 'WBC', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '上皮细胞(EC)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '/ul', key_value: { _key: '上皮细胞(EC)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '管型(CAST)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '/ul', key_value: { _key: '管型(CAST)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '结晶体(XTAL)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '/ul', key_value: { _key: '结晶体(XTAL)', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '粪常规：',
          required: false,
          displayControl: { check: false },
          cols: 3,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 2, rows: 1, key_value: { _key: '粪常规检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '外观：' },
            { type: 'radio', cols: 2, rows: 1, options: [ '软便', '硬便', '稀便', '糊便' ], key_value: { _key: '粪常规外观', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '粘液：' },
            { type: 'radio', cols: 2, rows: 1, options: [ '有', '无' ], key_value: { _key: '粪常规粘液', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '隐血：' },
            { type: 'radio', cols: 2, rows: 1, options: [ '阴性', '阳性' ], key_value: { _key: '粪常规隐血', _value: ''}, disabled: false},
          ]
        },
        {
          type: 'table',
          title: '肝功能：',
          required: false,
          displayControl: { check: false },
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 5, rows: 1, key_value: { _key: '肝功能检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '白蛋白(ALB)/球蛋白(GLO)：' },
            { type: 'input_double_with_text', cols: 2, rows: 1, left_text: '白蛋白(ALB)', center_text: 'g/L，球蛋白(GLO)', right_text: ' g/L', key_value: [{ _key: '白蛋白(ALB)', _value: ''}, { _key: '球蛋白(GLO)', _value: ''}] , disabled: false, calculate: { calculate_type: 'A/G', calculate_ref: 5, key_ref: ['白蛋白(ALB)', '球蛋白(GLO)'] } },
            { type: 'text', cols: 1, rows: 1, text: '白球比(A/G)：' },
            { type: 'input_with_text', cols: 2, rows: 1, right_text: '(自动计算)', key_value: { _key: '白球比(A/G)', _value: ''}, disabled: true},
            { type: 'text', cols: 1, rows: 1, text: '胆红素：' },
            { type: 'input_double_with_text', cols: 2, rows: 1, left_text: '总胆红素(TBIL)', center_text: 'umol/L，直接胆红素(DBIL)', right_text: 'umol/L ', key_value: [{ _key: '总胆红素(TBIL)', _value: ''}, { _key: '直接胆红素(DBIL)', _value: ''}] , disabled: false, calculate: { calculate_type: 'IBIL', calculate_ref: 9, key_ref: ['总胆红素(TBIL)', '直接胆红素(DBIL)'] } },
            { type: 'text', cols: 1, rows: 1, text: '间接胆红素(IBIL)：' },
            { type: 'input_with_text', cols: 2, rows: 1, right_text: ' umol/L(自动计算)', key_value: { _key: '间接胆红素(IBIL)', _value: ''}, disabled: true},
            { type: 'text', cols: 1, rows: 1, text: '总胆汁酸：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: ' umol/L', key_value: { _key: '总胆汁酸', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '谷丙转氨酶(ALT)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: ' U/L', key_value: { _key: '谷丙转氨酶(ALT)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '谷草转氨酶(AST)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: ' U/L', key_value: { _key: '谷草转氨酶(AST)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '碱性磷酸酶(ALP)：' },
            { type: 'input_with_text', cols: 2, rows: 1, right_text: ' U/L', key_value: { _key: '碱性磷酸酶(ALP)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: 'γ谷氨酰转肽酶(GGT)：' },
            { type: 'input_with_text', cols: 2, rows: 1, right_text: ' U/L', key_value: { _key: 'γ谷氨酰转肽酶(GGT)', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '肾功能：',
          required: false,
          displayControl: { check: false },
          cols: 8,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 7, rows: 1, key_value: { _key: '肾功能检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '肌酐(Sc)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'umol/L', key_value: { _key: '肌酐(Sc)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '尿素氮(BUN)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L', key_value: { _key: '尿素氮(BUN)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '尿酸(UA)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L', key_value: { _key: '尿酸(UA)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '胱抑素C(Cys_C)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mg/L', key_value: { _key: '胱抑素C(Cys_C)', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '电解质：',
          required: false,
          displayControl: { check: false },
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 5, rows: 1, key_value: { _key: '电解质检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '血钾(K)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L', key_value: { _key: '血钾(K)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '血钠(Na)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L', key_value: { _key: '血钠(Na)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '血氯(Cl)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L', key_value: { _key: '血氯(Cl)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '血钙(Ca)：' },
            { type: 'input_with_text', cols: 2, rows: 1, right_text: 'mg/L', key_value: { _key: '血钙(Ca)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '血镁(Mg)：' },
            { type: 'input_with_text', cols: 2, rows: 1, right_text: 'mg/L', key_value: { _key: '血镁(Mg)', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '心肌酶谱：',
          required: false,
          displayControl: { check: false },
          cols: 8,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 7, rows: 1, key_value: { _key: '心肌酶谱检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '肌酸激酶(CK)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'U/L', key_value: { _key: '肌酸激酶(CK)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '肌酸激酶同工酶(CK-MB)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'U/L', key_value: { _key: '肌酸激酶同工酶(CK-MB)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '乳酸脱氢酶 (LDH)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'U/L', key_value: { _key: '乳酸脱氢酶 (LDH)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '羟丁酸脱氢酶(HBDH)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'U/L', key_value: { _key: '羟丁酸脱氢酶(HBDH)', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '血糖：',
          required: false,
          displayControl: { check: false },
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 5, rows: 1, key_value: { _key: '血糖检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '空腹血糖：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L', key_value: { _key: '空腹血糖', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '随机血糖：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L', key_value: { _key: '随机血糖', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '餐后两小时血糖：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L', key_value: { _key: '餐后两小时血糖', _value: ''}, disabled: false},
          ]
        },
        {
          type: 'table',
          title: '糖化血红蛋白：',
          required: false,
          displayControl: { check: false },
          cols: 4,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 1, rows: 1, key_value: { _key: '糖化血红蛋白检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '糖化血红蛋白(HbAlc)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '%', key_value: { _key: '糖化血红蛋白(HbAlc)', _value: ''}, disabled: false},
          ]
        },
        {
          type: 'table',
          title: '肌钙蛋白：',
          required: false,
          displayControl: { check: false },
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 1, rows: 1, key_value: { _key: '肌钙蛋白检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '肌钙蛋白(CTnI)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'pg/mL', key_value: { _key: '肌钙蛋白(CTnI)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '肌钙蛋白(CTnT)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'pg/mL', key_value: { _key: '肌钙蛋白(CTnT)', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '肌红蛋白：',
          required: false,
          displayControl: { check: false },
          cols: 4,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 1, rows: 1, key_value: { _key: '肌红蛋白检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '肌红蛋白Myo(Mb)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'ug/L', key_value: { _key: '肌红蛋白Myo(Mb)', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '血脂：',
          required: false,
          displayControl: { check: false },
          cols: 4,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 3, rows: 1, key_value: { _key: '血脂检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '总胆固醇(CHO)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L ', key_value: { _key: '总胆固醇(CHO)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '甘油三酯(TG)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L ', key_value: { _key: '甘油三酯(TG)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '低密度脂蛋白胆固醇(LDL-C)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L ', key_value: { _key: '低密度脂蛋白胆固醇(LDL-C)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '高密度脂蛋白胆固醇(HDL-C)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mmol/L ', key_value: { _key: '高密度脂蛋白胆固醇(HDL-C)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '载脂蛋白AI(apoAI)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'g/L', key_value: { _key: '载脂蛋白AI(apoAI)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '载脂蛋白B(apoB)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'g/L', key_value: { _key: '载脂蛋白B(apoB)', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '凝血六项：',
          required: false,
          displayControl: { check: false },
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 5, rows: 1, key_value: { _key: '凝血六项检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: 'D-二聚体：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'ug/L', key_value: { _key: '总D-二聚体', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '凝血酶原时间(PT)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '秒', key_value: { _key: '凝血酶原时间(PT)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '凝血酶原比值(PTR)：' },
            { type: 'input_with_text', cols: 1, rows: 1, key_value: { _key: '凝血酶原比值(PTR)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '凝血酶原标准化比值(INR)：' },
            { type: 'input_with_text', cols: 1, rows: 1, key_value: { _key: '凝血酶原标准化比值(INR)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '活化部分凝血活酶时间(APTT)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '秒', key_value: { _key: '活化部分凝血活酶时间(APTT)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '凝血酶时间(TT)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '秒', key_value: { _key: '凝血酶时间(TT)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '凝血酶时间比值(TTR)：' },
            { type: 'input_with_text', cols: 1, rows: 1, key_value: { _key: '凝血酶时间比值(TTR)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '纤维蛋白原含量(FIB)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'g/L', key_value: { _key: '纤维蛋白原含量(FIB)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '纤维蛋白原降解产物(FDP)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mg/L', key_value: { _key: '纤维蛋白原降解产物(FDP)', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '血清：',
          required: false,
          displayControl: { check: false },
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 5, rows: 1, key_value: { _key: '血清检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '脑利钠肽前体(NT-ProBNP)或脑利钠肽(BNP)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'pg/mL', key_value: { _key: '脑利钠肽前体(NT-ProBNP)或脑利钠肽(BNP)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '高敏C反应蛋白(Hs-CRP)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mg/L', key_value: { _key: '高敏C反应蛋白(Hs-CRP)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '同型半胱胺酸(HCY)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'umol/L', key_value: { _key: '同型半胱胺酸(HCY)', _value: ''}, disabled: false},
          ]
        },
        {
          type: 'table',
          title: '24小时尿白蛋白：',
          required: false,
          displayControl: { check: false },
          cols: 4,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 1, rows: 1, key_value: { _key: '24小时尿白蛋白检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '24小时尿白蛋白：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mg/24h', key_value: { _key: '24小时尿白蛋白', _value: ''}, disabled: false},
          ]
        },
        {
          type: 'table',
          title: '心电图：',
          required: false,
          displayControl: { check: false },
          cols: 4,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 1, rows: 1, key_value: { _key: '心电图检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '心律：' },
            { type: 'radio', cols: 1, rows: 1, options: ['齐', '不齐'], key_value:{ _key: '', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '心率：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '次/分', key_value: { _key: '心电图_心率', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '心电轴：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '次/分', key_value: { _key: '心电轴', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 2, text: 'R-R间期和Q-T间期：' },
            { type: 'input_double_with_text', cols: 1, rows: 2, left_text: 'R-R间期：', center_text: '秒， Q-T间期：', right_text: '秒', key_value: [{ _key: 'R-R间期', _value: ''}, { _key: 'Q-T间期', _value: ''}], disabled: false, calculate: { calculate_type: 'QTC', calculate_ref: 11, key_ref: ['R-R间期', 'Q-T间期'] }},
            { type: 'text', cols: 1, rows: 2, text: 'QTC：' },
            { type: 'input_with_text', cols: 1, rows: 2, right_text: '自动计算', key_value: { _key: 'QTC', _value: ''}, disabled: true},
            { type: 'text', cols: 1, rows: 1, text: 'P-R间期：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '秒', key_value: { _key: 'P-R间期', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: 'QRS时间：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '秒', key_value: { _key: 'QRS时间', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: 'RV5和SV1：' },
            { type: 'input_double_with_text', cols: 1, rows: 1, left_text: 'RV5：', center_text: 'mV， SV1：', right_text: 'mv', key_value: [{ _key: 'RV5', _value: ''}, { _key: 'SV1', _value: ''}], disabled: false, calculate: { calculate_type: 'RV5+SV1', calculate_ref: 19, key_ref: ['RV5', 'SV1'] }},
            { type: 'text', cols: 1, rows: 1, text: 'RV5+SV1：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '自动计算', key_value: { _key: 'RV5+SV1', _value: ''}, disabled: true},
            { type: 'text', cols: 1, rows: 1, text: '上传心电图：' },
            { type: 'file', cols: 3, rows: 1, key_value: { _key: '心电图', _value: {} }, disabled: true, fileName: '没有上传任何文件'},
          ]
        },
        {
          type: 'table',
          title: '心脏超声：',
          required: false,
          displayControl: { check: false },
          cols: 8,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 3, rows: 1, key_value: { _key: '心脏超声检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '心脏超声上传：' },
            { type: 'file', cols: 3, rows: 1, key_value: { _key: '心脏超声图', _value: {} }, disabled: true, fileName: '没有上传任何文件'},
            { type: 'text', cols: 1, rows: 1, text: '主动脉根部内径(AORD)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '主动脉根部内径(AORD)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '瓣膜开放大小(VOS)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '瓣膜开放大小(VOS)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '左房内径(LAD)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '左房内径(LAD)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '室间隔厚度\n(IVST/IVST-W)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '室间隔厚度(IVST/IVST-W)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '室间隔搏幅(IVST-S)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '室间隔搏幅(IVST-S)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '左室舒张末内径\n(LVDd/LVEDD)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '左室舒张末内径(LVDd/LVEDD)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '左室收缩末内径\n(LVSd/LVESD)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '左室收缩末内径(LVSd/LVESD)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '左室后壁厚度\n(LVPWT/LVPWT-W)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '左室后壁厚度(LVPWT/LVPWT-W)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '左室后壁搏幅\n(LVPWT-S)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '左室后壁搏幅(LVPWT-S)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '右室内径(RVID)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '右室内径(RVID)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '升主动脉内径(AOLPAD)：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '升主动脉内径(AOLPAD)', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: 'EF：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '%', key_value: { _key: 'EF', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: 'FS：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: '%', key_value: { _key: 'FS', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: 'SV：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'ml', key_value: { _key: 'SV', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: 'CO：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'L/min', key_value: { _key: 'CO', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: 'E/A：' },
            { type: 'input_with_text', cols: 1, rows: 1, key_value: { _key: 'E/A', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '颈动脉超声：',
          required: false,
          displayControl: { check: false },
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 5, rows: 1, key_value: { _key: '颈动脉超声检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '颈总动脉右IMT：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '颈总动脉右IMT', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '颈总动脉左IMT：' },
            { type: 'input_with_text', cols: 1, rows: 1, right_text: 'mm', key_value: { _key: '颈总动脉左IMT', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '动脉粥样硬化斑块超声表现：' },
            { type: 'radio', cols: 1, rows: 1, options: ['无', '有'], key_value: { _key: '动脉粥样硬化斑块超声表现', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: 'X线：',
          required: false,
          displayControl: { check: false },
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 2, rows: 1, key_value: { _key: 'X线检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '心脏形态：' },
            { type: 'radio', cols: 2, rows: 1, options: [ '烧瓶型', '球型', '梨型', '靴型', '正常型'], key_value: { _key: '心脏形态', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '动脉结突出：' },
            { type: 'input_with_text', cols: 1, rows: 1, options: [ '否', '是' ], key_value: { _key: '动脉结突出', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '心腰：' },
            { type: 'radio', cols: 1, rows: 1, options: ['平直', '凹陷', '隆起'], key_value: { _key: '心腰', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '心胸比：' },
            { type: 'input_with_text', cols: 1, rows: 1, key_value: { _key: '心胸比', _value: ''}, disabled: false}
          ]
        },
        {
          type: 'table',
          title: '眼底检查：',
          required: false,
          displayControl: { check: false },
          cols: 6,
          layout: [
            { type: 'text', cols: 1, rows: 1, text: '检查时间：' },
            { type: 'date', cols: 1, rows: 1, key_value: { _key: '眼底检查时间', '_value': '' } },
            { type: 'text', cols: 1, rows: 1, text: '视网膜出血或渗出：' },
            { type: 'radio', cols: 1, rows: 1, options: [ '是', '否' ], key_value: { _key: '视网膜出血或渗出', _value: ''}, disabled: false},
            { type: 'text', cols: 1, rows: 1, text: '视乳头水肿：' },
            { type: 'radio', cols: 1, rows: 1, options: ['是', '否'], key_value: { _key: '视乳头水肿', _value: ''}, disabled: false}
          ]
        }
      ]
    }
  ];
}
